config/routes.rb
Rails.application.routes.draw do
  # added after installing devise and running rails g devise User
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # ROUTE DEFINITIONS
  # can define request types for routes
  # route order matters prevent endpoints from being read as parameter
   # create a new blog post action
   get "blog_posts/new" => "blog_posts#new", as: :new_blog_post
  # get, post, put, patch, delete
  #  => syntax same as to:
  # can give rout a variable name to be referenced easily in app (as: :blog_post)
  get "blog_posts/:id" => "blog_posts#show", as: :blog_post
  # <Route path="/blog_posts/:id" element={<BlogPosts.Show />} />
  # blog_post_path(<id>) -> returns the path for the show action of the blog post with the given id
  # blog_post_url(<id>) -> returns the full URL for the show action of the blog post with the given id

  # edit route so post/:id/edit -> edit action
  get "blog_posts/:id/edit" => "blog_posts#edit", as: :edit_blog_post

  # patch route for update action
  #  no need for variable (path helper) because already defined in show route that has same endpoint
  # then need to add update action in controller -> #update
  patch "blog_posts/:id" => "blog_posts#update"

  # delete route for destroy action -> no variable again b/c already defined in show route that has same endpoint
  # then need to add destroy action in controller -> #destroy
  delete "blog_posts/:id" => "blog_posts#destroy"

  # looking for blog_posts_path because it needs to know where to submit the form -> need route for POST action (handle submit request) -> variable is PLURAL
  post "blog_posts" => "blog_posts#create", as: :blog_posts
 
  


  # Defines the root path route ("/")
  # Root route can be anywhere in the file, but conventionally at the bottom
  # blog_posts tells Rails to look for BlogPostsController due to syntax formatting of BlogPosts -> blog_posts
  # blog_posts → looks for app/controllers/blog_posts_controller.rb
  # #index tells Rails to call the index method in that controller -> hence creation of class and creation of index method (action)
  # controller class must be BlogPostsController (Rails automatically converts snake_case to CamelCase
  # The index method in the controller automatically looks for a view in app/views/blog_posts/index.html.erb
  # The index.html.erb file is automatically rendered when the index action is called
  root "blog_posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application.tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose">
    <%= yield %>
    <%# flash messages from devise %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%# nav bar %>
    <%# if user is signed in, show links to sign in and sign up %>
    <% if user_signed_in? %>
      <nav>
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "New Blog Post", new_blog_post_path %></li>
          <li><%= link_to "Blog Posts", root_path %></li>
          <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </nav>
    <% else %>
      <nav>
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        </ul>
      </nav>
    <% end %>
  </body>
</html>